name: Run tests

on:
  workflow_run:
      workflows: ["Check Compilation"]
      branches: [master]
      types:
        - completed

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make tests_run

      - name: Show coverage
        run: make coverage

  functionnal-tests:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Run tests
        run: ./test.sh