name: Check compilation
on:
  push:
    branches:
    - master
jobs:
  compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:devel
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Check if binary exists
        run: ls my_hello