name: Check compilation
on:
	push:
		branches:
		- master
jobs:
	compilation:
		runs-on: ubuntu-latest
		container: epitechcontent/epitest-docker:devel
		steps:
		#Checkout code
			- name: Checkout code
			uses: actions/checkout@v2
		#Run
			- name: Build
			run: make
		#Compil ?
			- name: Check if binary exists 
			run: ls my_hello 